[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov-report term-missing --cov=client --cov=server"
testpaths = [
    "tests",
]
pythonpath = "."
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore:coroutine",
]