sentences = [
    "There's a reason that roses have thorns.",
    "All they could see was the blue water surrounding their sailboat.",
    "Today I heard something new and unmemorable.",
    "Patricia found the meaning of life in a bowl of Cheerios.",
    "The manager of the fruit stand always sat and only sold vegetables.",
    "The hawk didn't understand why the ground squirrels didn't want to be his friend.",
    "She did her best to help him.",
    "It's much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball.",
    "She traveled because it cost the same as therapy and was a lot more enjoyable.",
    "Each person who knows you has a different perception of who you are.",
    "I've always wanted to go to Tajikistan, but my cat would miss me.",
    "Be careful with that butter knife.",
    "The quick brown fox jumps over the lazy dog.",
    "The pigs were insulted that they were named hamburgers.",
    "There are no heroes in a punk rock band.",
    "Jason lived his life by the motto, Anything worth doing is worth doing poorly.",
    "I want a giraffe, but I'm a turtle eating waffles.",
    "A suit of armor provides excellent sun protection on hot days.",
    "She always speaks to him in a loud voice.",
    "More RVs were seen in the storage lot than at the campground.",
    "As he waited for the shower to warm, he noticed that he could hear water change temperature.",
    "It's not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.",
    "If any cop asks you where you were, just say you were visiting Kansas.",
    "Every manager should be able to recite at least ten nursery rhymes backward.",
    "The teens wondered what was kept in the red shed on the far edge of the school grounds.",
    "Nudist colonies shun fig-leaf couture.",
    "He figured a few sticks of dynamite were easier than a fishing pole to catch fish.",
    "Happiness can be found in the depths of chocolate pudding.",
    "I come from a tribe of head-hunters, so I will never need a shrink.",
    "The stench from the feedlot permeated the car despite having the air conditioning on recycled air.",
    "She used her own hair in the soup to give it more flavor.",
    "I can't believe this is the eighth time I'm smashing open my piggy bank on the same day!",
    "I ate a sock because people on the Internet told me to.",
    "He had a hidden stash underneath the floorboards in the back room of the house.",
    "Tomorrow will bring something new, so leave today as a memory.",
    "She wrote him a long letter, but he didn't read it.",
    "The crowd yells and screams for more memes.",
    "I want to buy a onesie… but know it won't suit me.",
    "If you really strain your ears, you can just about hear the sound of no one giving a damn.",
    "The rain pelted the windshield as the darkness engulfed us.",
    "Peter found road kill an excellent way to save money on dinner.",
    "Trash covered the landscape like sprinkles do a birthday cake.",
    "Jenny made the announcement that her baby was an alien.",
    "I'll have you know I've written over fifty novels",
    "Two seats were vacant.",
    "I don't respect anybody who can't tell the difference between Pepsi and Coke.",
    "The shark-infested South Pine channel was the only way in or out.",
    "There aren't enough towels in the world to stop the sewage flowing from his mouth.",
    "He had unknowingly taken up sleepwalking as a nighttime hobby.",
    "The child's favorite Christmas gift was the large box her father's lawnmower came in.",
]
